[tool.poetry]
name = "vidl"
version = "3.4.6"
description = "Python script to download video/audio, built with youtube-dl"
authors = ["KH <kasperkh.kh@gmail.com>"]

readme = 'README.md'

repository = "https://github.com/spectralkh/vidl"
homepage = "https://vidl.kasp.io"

keywords = ['youtube', 'download', 'video', 'audio', 'music']

[tool.poetry.dependencies]
python = "^3.5"
youtube-dl = ",*"
colorama = "^0.3.9"
colorboy = "^1.0.1"
mutagen = "^1.42"
deep-filter = "^1.0"
appdirs = "^1.4"

[tool.poetry.dev-dependencies]
pylint = "*"

[tool.poetry.scripts]
vidl = 'vidl.app:main'
